name: auto_flow
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter_screenutil:
  intl: ^0.19.0
  pin_code_fields: 
  shimmer: ^3.0.0
  shared_preferences: 
  flutter_secure_storage: ^10.0.0 
  http:
  file_picker:
  path:
  provider:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_html: ^3.0.0



dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: true
  ios: true

  adaptive_icon_background: "#0FCCBF" 
  adaptive_icon_foreground: assets/icon/icon_foreground.png
  image_path: assets/icon/playstore-icon.png


flutter:
  assets:
    - assets/user/
    - assets/logo/
    - assets/icon/

  uses-material-design: true
